import type { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import { ContainerRegistrationKeys, Modules } from "@medusajs/framework/utils"
import { EmailTemplates, resolveTemplateKey } from "../../../../../modules/email-notifications/templates"
import { resolveBillingEntity } from "../../../../../utils/resolve-billing-entity"
import { logEmailActivity } from "../../../../../utils/email-logger"
import { renderEmailToHtml } from "../../../../../utils/render-email-html"
import { getProjectEmailConfig, getEmailSubject } from "../../../../../utils/project-email-config"

/**
 * POST /admin/custom-orders/:id/resend-confirmation
 *
 * Re-sends the order confirmation email (the one customers receive right
 * after payment). Mirrors the email composition in subscribers/order-placed.ts
 * — must stay in sync with it. No idempotency guard here: resending is the
 * whole point of this endpoint.
 */
export async function POST(
  req: MedusaRequest,
  res: MedusaResponse
): Promise<void> {
  const { id } = req.params
  try {
    const notificationService = req.scope.resolve(Modules.NOTIFICATION) as any
    const orderModuleService = req.scope.resolve(Modules.ORDER) as any

    const order = await orderModuleService.retrieveOrder(id, {
      relations: ["items", "summary", "shipping_address", "billing_address"],
    })

    if (!order?.email) {
      res.status(400).json({ error: "Order has no customer email" })
      return
    }

    // Retrieve full shipping address
    let shippingAddress: any = null
    try {
      if (order.shipping_address) {
        shippingAddress = await orderModuleService.orderAddressService_.retrieve(
          order.shipping_address.id
        )
      }
    } catch {
      shippingAddress = order.shipping_address
    }

    // Retrieve full billing address
    let billingAddress: any = null
    try {
      if (order.billing_address) {
        billingAddress = await orderModuleService.orderAddressService_.retrieve(
          order.billing_address.id
        )
      }
    } catch {
      // Will fall back to shipping address in template
    }

    // Detect payment method from payment collections — same mapping as order-placed.ts
    let paymentMethod = "Online betaling"
    try {
      const queryService = req.scope.resolve(ContainerRegistrationKeys.QUERY)
      const { data: paymentData } = await queryService.graph({
        entity: "order",
        fields: [
          "payment_collections.payments.provider_id",
          "payment_collections.payments.data",
        ],
        filters: { id },
      })
      const payments =
        paymentData?.[0]?.payment_collections?.flatMap(
          (pc: any) => pc.payments || []
        ) || []
      const firstPayment = payments[0]
      if (firstPayment) {
        const providerId = (firstPayment.provider_id || "").toLowerCase()
        const payData = firstPayment.data || {}
        const mollieMethod = (payData.mollieMethod || payData.method || "").toLowerCase()

        if (mollieMethod === "ideal" || payData.molliePaymentId?.includes("ideal")) {
          paymentMethod = "iDEAL"
        } else if (mollieMethod === "bancontact") {
          paymentMethod = "Bancontact"
        } else if (mollieMethod === "creditcard" || mollieMethod === "credit_card") {
          paymentMethod = "Credit Card"
        } else if (mollieMethod === "sofort" || mollieMethod === "sofortbanking") {
          paymentMethod = "SOFORT"
        } else if (mollieMethod === "eps") {
          paymentMethod = "EPS"
        } else if (mollieMethod === "giropay") {
          paymentMethod = "Giropay"
        } else if (providerId.includes("klarna") || mollieMethod.includes("klarna")) {
          paymentMethod = "Klarna"
        } else if (providerId.includes("stripe")) {
          paymentMethod = "Credit Card"
        } else if (providerId.includes("paypal") || mollieMethod === "paypal") {
          paymentMethod = "PayPal"
        } else if (providerId.includes("comgate")) {
          paymentMethod = "Comgate"
        } else if (providerId.includes("przelewy") || mollieMethod.includes("przelewy")) {
          paymentMethod = "Przelewy24"
        } else if (mollieMethod) {
          paymentMethod = mollieMethod.charAt(0).toUpperCase() + mollieMethod.slice(1)
        }
      }
    } catch (payErr: any) {
      console.warn("[Resend Confirmation] Could not detect payment method:", payErr.message)
    }

    // Custom order number (already generated by order-placed-custom-number subscriber)
    let displayId = order.metadata?.custom_order_number
    if (!displayId) {
      const countryCode = (
        shippingAddress?.country_code ||
        order.shipping_address?.country_code ||
        ""
      ).toUpperCase() || "XX"
      const year = new Date(order.created_at || Date.now()).getFullYear()
      displayId = `${countryCode}${year}-${order.display_id || order.id}`
    }

    // Resolve billing entity for footer
    let billingEntity: any = null
    try {
      billingEntity = await resolveBillingEntity(req.scope, id)
    } catch (err: any) {
      console.warn("[Resend Confirmation] Could not resolve billing entity:", err.message)
    }

    // Project-specific email config + template
    const projectConfig = getProjectEmailConfig(order)
    const templateKey = resolveTemplateKey(EmailTemplates.ORDER_PLACED, projectConfig.project)

    const emailSubject = getEmailSubject(projectConfig, "orderPlaced").replace("{id}", String(displayId))
    const emailPreview = getEmailSubject(projectConfig, "orderPlacedPreview")

    const emailData = {
      emailOptions: {
        replyTo: projectConfig.replyTo,
        subject: emailSubject,
      },
      order,
      shippingAddress,
      billingAddress,
      paymentMethod,
      billingEntity,
      preview: emailPreview,
    }

    await notificationService.createNotifications({
      to: order.email,
      channel: "email",
      template: templateKey,
      ...(projectConfig.fromEmail ? { from: projectConfig.fromEmail } : {}),
      data: emailData,
    })

    // Render HTML for email preview in timeline
    const htmlBody = await renderEmailToHtml(templateKey, emailData).catch(() => "")

    await logEmailActivity(orderModuleService, id, {
      template: "order_confirmation_resend",
      subject: emailSubject,
      to: order.email,
      status: "sent",
      ...(htmlBody ? { html_body: htmlBody } : {}),
    }).catch((err: any) =>
      console.warn("[Resend Confirmation] Could not log email activity:", err.message)
    )

    console.log(`[Resend Confirmation] Re-sent order confirmation to ${order.email} for order ${id}`)

    res.json({ success: true, to: order.email, subject: emailSubject })
  } catch (error: any) {
    console.error("[Resend Confirmation] Error:", error)
    res.status(500).json({ error: error.message || "Failed to resend order confirmation" })
  }
}
